steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.api'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/roleup-api'
      - '.'
images:
  - 'asia.gcr.io/$PROJECT_ID/roleup-api'
